ersion: "3.7"

services:
  portainer:
   #image: portainer/portainer-ce:latest # Uncomment out if you use the community open-source version
   image: portainer/portainer-ee:latest
   container_name: portainer
   hostname: portainer
   ports:
   - 8000:8000
   - 9000:9000
   - 9443:9443
   volumes:
   - ./data:/data
   - /var/run/docker.sock:/var/run/docker.sock
   restart: always

volumes:
  data:
    external:
      name: portainer_data
